name: Coverage
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            # Install dependencies and bundle the software
            - name: Initialize
              run: |
                  npm ci
                  npm run test

            # Run the coverage reporter
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
