name: Coverage
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout Repository
              uses: actions/checkout@v3

            # Install NodeJS
            - name: Install NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: "20.10.0"

            # Install dependencies and bundle the software
            - name: Initialize
              run: |
                  npm ci
                  npm run test

            # Run the coverage reporter
            - uses: ArtiomTr/jest-coverage-report-action@v2
